#! /bin/sh
# postrm script for icecast2

set -e

case "$1" in
    purge)
	rm -rf /var/log/icecast2

	if id icecast >/dev/null 2>&1; then
	    deluser icecast
	fi

	# Remove group only if empty
	if getent group icecast | awk -F: ' { print $4 } ' | egrep -cq '^$'; then
	    groupdel icecast
	fi
	;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

	;;
    *)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
esac

#DEBHELPER#

exit 0
