#! /bin/sh
# preinst script for icecast2

set -e

case "$1" in
    install|upgrade)
        if [ "$1" = "upgrade" ]
        then
            start-stop-daemon --stop --quiet --oknodo  \
                --exec /usr/bin/icecast2 2>/dev/null || true
        fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

